### ISSUE TITLE
update db/seed.rb

### ISSUE THREAD

**Issue by treyssatvincent** [bastienrobert/TradFood#6]
Please update seed.rb with private heroku instance's database.

**Comment by bastienrobert** [comment]
Do it and create a new pull request.
Thanks,

**Comment by treyssatvincent** [comment]
I havn't acess to heroku instance's database. 
1) Push [this commit](https://github.com/bastienrobert/TradFood/commit/00b93f78acfd696d1b14347cd20f313458e98f06) on heroku
2) run `rake db:seed:dump` on heroku
3) replace the db/seed.rb on this repo with the one on heroku.

If you need more info on the gem : [https://github.com/rroblak/seed_dump](https://github.com/rroblak/seed_dump)

**Comment by bastienrobert** [comment]
Please send me your email in DM, I will add it to Heroku contributors.
Thanks, issue closed.
